// Mode rapide — génération d'un chiffrage en ouvrages complets (Guide §8.1).
// Logique pure et testable : un input (type de projet, surface, gamme, postes
// cochés avec quantités) -> des lignes de devis fondées sur OCREN-* / OCMOB-*.
//
// Le mode rapide ne descend JAMAIS au poste élémentaire : un forfait par grand
// poste, à raffiner ensuite en mode détaillé.

import { ligneDepuisPoste } from "./engine";
import type {
  Gamme,
  LigneDevis,
  ParametresDevis,
  PosteBPU,
  TauxTVA,
} from "./types";

/** Type de projet proposé en mode rapide. */
export type TypeProjetRapide =
  | "renovation_appartement"
  | "renovation_maison"
  | "renovation_studio"
  | "renovation_haussmannien"
  | "renovation_energetique"
  | "adaptation_pmr"
  | "extension"
  | "surelevation"
  | "neuf_maconne"
  | "amenagement_commercial"
  | "chr_restaurant"
  | "amenagement_tertiaire"
  | "erp_sante"
  // Conservés pour compatibilité (anciens devis) ; non affichés.
  | "erp"
  | "neuf";

export const TYPES_PROJET: { value: TypeProjetRapide; label: string }[] = [
  { value: "renovation_appartement", label: "Rénovation appartement" },
  { value: "renovation_maison", label: "Rénovation maison" },
  { value: "renovation_studio", label: "Studio / locatif éco" },
  { value: "renovation_haussmannien", label: "Haussmannien / patrimonial" },
  { value: "renovation_energetique", label: "Rénovation énergétique" },
  { value: "adaptation_pmr", label: "Adaptation PMR / senior" },
  { value: "extension", label: "Extension" },
  { value: "surelevation", label: "Surélévation" },
  { value: "neuf_maconne", label: "Maison neuve maçonnée" },
  { value: "amenagement_commercial", label: "Commerce / boutique (ERP)" },
  { value: "chr_restaurant", label: "CHR / Restaurant (ERP)" },
  { value: "amenagement_tertiaire", label: "Bureaux / tertiaire" },
  { value: "erp_sante", label: "ERP de santé (cabinet)" },
];

/** Un ouvrage complet sélectionnable en mode rapide. */
export interface OuvrageRapide {
  /** Code BPU (ouvrage complet). */
  code: string;
  /** Libellé court orienté client. */
  label: string;
  /** Groupe d'affichage dans le wizard. */
  groupe: string;
  /** Aide à la saisie (ex. "m² de la pièce"). */
  aide: string;
  /** Types de projet pour lesquels l'ouvrage est proposé. */
  pour: TypeProjetRapide[];
  /** Quantité proposée par défaut à partir de la surface SHAB. */
  qteDefaut: (shab: number) => number;
  /** Coché par défaut à l'ouverture du wizard. */
  coche?: boolean;
  /** Sous-bloc à l'intérieur d'un groupe (sous-titre). */
  sousGroupe?: string;
  /**
   * Identifiant de sous-choix : les ouvrages partageant le même sousChoixId
   * (dans un même type) sont MUTUELLEMENT EXCLUSIFS (rendus en radio).
   */
  sousChoixId?: string;
  /** Éligible TVA 5,5 % (amélioration énergétique). Prioritaire sur le set legacy. */
  eligible55?: boolean;
}

// Les listes de types (RENO/RENO_PLUS/ENERGETIQUE) sont désormais inlinées
// dans chaque pour[] (régénération du catalogue, audit de parcours 2026-06-30).

/**
 * Catalogue des ouvrages complets du mode rapide.
 * Ne référence que des codes présents dans le BPU (OCREN-*, OCMOB-*).
 */
export const OUVRAGES_RAPIDE: OuvrageRapide[] = [
  {
    code: "OCREN-07",
    label: "Rénovation globale (hors cuisine & SDB)",
    groupe: "Global",
    aide: "m² SHAB concernés",
    pour: ["renovation_appartement", "renovation_maison"],
    qteDefaut: (s) => s,
    coche: true,
  },
  {
    code: "OCREN-06",
    label: "Réfection pièce de vie",
    groupe: "Pièces",
    aide: "m² de la pièce",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio"],
    qteDefaut: () => 0,
  },
  {
    code: "OCREN-01",
    label: "Salle de bains clé en main",
    groupe: "Pièces",
    aide: "m² de SDB (cumul)",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio", "renovation_haussmannien", "adaptation_pmr"],
    qteDefaut: () => 5,
  },
  {
    code: "OCREN-02",
    label: "Cuisine clé en main",
    groupe: "Pièces",
    aide: "ml de meubles",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio", "renovation_haussmannien", "adaptation_pmr"],
    qteDefaut: () => 4,
  },
  {
    code: "OCREN-03",
    label: "WC complet",
    groupe: "Pièces",
    aide: "nombre de WC",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio", "renovation_haussmannien", "adaptation_pmr"],
    qteDefaut: () => 1,
  },
  {
    code: "OCREN-13",
    label: "Salle de bains PMR sécurisée clé en main",
    groupe: "Pièces",
    aide: "nombre de SDB PMR",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio", "renovation_haussmannien", "adaptation_pmr"],
    qteDefaut: () => 1,
  },
  {
    code: "OCREN-04",
    label: "Isolation intérieure (ITI)",
    groupe: "Enveloppe",
    sousGroupe: "Isolation des murs",
    sousChoixId: "iso-murs",
    aide: "m² de murs",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio", "renovation_energetique"],
    qteDefaut: (s) => s,
    eligible55: true,
  },
  {
    code: "OCREN-05",
    label: "Isolation extérieure (ITE)",
    groupe: "Enveloppe",
    sousGroupe: "Isolation des murs",
    sousChoixId: "iso-murs",
    aide: "m² de façade",
    pour: ["renovation_maison", "renovation_energetique"],
    qteDefaut: () => 0,
    eligible55: true,
  },
  {
    code: "OCREN-09",
    label: "Ravalement de façade",
    groupe: "Enveloppe",
    aide: "m² de façade",
    pour: ["renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "OCREN-10",
    label: "Remplacement menuiseries extérieures",
    groupe: "Enveloppe",
    aide: "m² de menuiseries",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio", "renovation_energetique"],
    qteDefaut: () => 0,
  },
  {
    code: "OCREN-11",
    label: "Électricité complète (mise aux normes)",
    groupe: "Lots techniques",
    aide: "m² SHAB",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio"],
    qteDefaut: () => 0,
  },
  {
    code: "OCREN-12",
    label: "Plomberie complète",
    groupe: "Lots techniques",
    aide: "m² SHAB",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio"],
    qteDefaut: () => 0,
  },
  {
    code: "OCREN-14",
    label: "PAC air-eau clé en main",
    groupe: "Lots techniques",
    sousGroupe: "Chauffage",
    sousChoixId: "chauffage",
    aide: "nombre d'installations",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio", "renovation_energetique"],
    qteDefaut: () => 0,
    eligible55: true,
  },
  {
    code: "CVC-96",
    label: "Radiateurs gaz / élec (remplacement)",
    groupe: "Lots techniques",
    sousGroupe: "Chauffage",
    sousChoixId: "chauffage",
    aide: "logement",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio", "renovation_energetique"],
    qteDefaut: () => 0,
  },
  {
    code: "OCREN-08",
    label: "Mur porteur — création d'ouverture",
    groupe: "Structure",
    aide: "nombre d'ouvertures",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio"],
    qteDefaut: () => 1,
  },
  {
    code: "OCMOB-09",
    label: "Ossature bois — hors d'eau / hors d'air",
    groupe: "Extension ossature bois",
    sousGroupe: "Structure & finition (1 au choix)",
    sousChoixId: "ext-fin",
    aide: "m² SHON",
    pour: ["extension"],
    qteDefaut: (s) => s,
  },
  {
    code: "OCMOB-10",
    label: "Ossature bois — clé en main TCE (tuiles)",
    groupe: "Extension ossature bois",
    sousGroupe: "Structure & finition (1 au choix)",
    sousChoixId: "ext-fin",
    aide: "m² SHON",
    pour: ["extension"],
    qteDefaut: (s) => s,
    coche: true,
  },
  {
    code: "OCMOB-16",
    label: "Ossature bois — clé en main TCE (zinc)",
    groupe: "Extension ossature bois",
    sousGroupe: "Structure & finition (1 au choix)",
    sousChoixId: "ext-fin",
    aide: "m² SHON",
    pour: ["extension"],
    qteDefaut: (s) => s,
  },
  {
    code: "OCMOB-15",
    label: "Ossature bois — clé en main TCE (toit-terrasse)",
    groupe: "Extension ossature bois",
    sousGroupe: "Structure & finition (1 au choix)",
    sousChoixId: "ext-fin",
    aide: "m² SHON",
    pour: ["extension"],
    qteDefaut: (s) => s,
  },
  {
    code: "OCMAC-04",
    label: "Maçonnée — hors d'eau / hors d'air",
    groupe: "Extension ossature bois",
    sousGroupe: "Structure & finition (1 au choix)",
    sousChoixId: "ext-fin",
    aide: "m² SHON",
    pour: ["extension"],
    qteDefaut: (s) => s,
  },
  {
    code: "OCMAC-03",
    label: "Maçonnée — clé en main TCE",
    groupe: "Extension ossature bois",
    sousGroupe: "Structure & finition (1 au choix)",
    sousChoixId: "ext-fin",
    aide: "m² SHON",
    pour: ["extension"],
    qteDefaut: (s) => s,
  },
  {
    code: "OCMOB-19",
    label: "Aménagement intérieur (si hors d'air seul)",
    groupe: "Extension ossature bois",
    aide: "m² (compléter un HE/HA)",
    pour: ["extension", "surelevation"],
    qteDefaut: () => 0,
  },
  {
    code: "OCMOB-11",
    label: "Ossature bois — hors d'eau / hors d'air",
    groupe: "Surélévation ossature bois",
    sousGroupe: "Structure & finition (1 au choix)",
    sousChoixId: "sur-fin",
    aide: "m² SHON",
    pour: ["surelevation"],
    qteDefaut: (s) => s,
  },
  {
    code: "OCMOB-12",
    label: "Ossature bois — clé en main TCE",
    groupe: "Surélévation ossature bois",
    sousGroupe: "Structure & finition (1 au choix)",
    sousChoixId: "sur-fin",
    aide: "m² SHON",
    pour: ["surelevation"],
    qteDefaut: (s) => s,
    coche: true,
  },
  {
    code: "OCMOB-18",
    label: "Ossature bois — clé en main TCE (toiture tuiles)",
    groupe: "Surélévation ossature bois",
    sousGroupe: "Structure & finition (1 au choix)",
    sousChoixId: "sur-fin",
    aide: "m² SHON",
    pour: ["surelevation"],
    qteDefaut: (s) => s,
  },
  {
    code: "OCMOB-17",
    label: "Ossature bois — clé en main TCE (toit-terrasse)",
    groupe: "Surélévation ossature bois",
    sousGroupe: "Structure & finition (1 au choix)",
    sousChoixId: "sur-fin",
    aide: "m² SHON",
    pour: ["surelevation"],
    qteDefaut: (s) => s,
  },
  {
    code: "OCMAC-05",
    label: "Maçonnée — clé en main TCE",
    groupe: "Surélévation ossature bois",
    sousGroupe: "Structure & finition (1 au choix)",
    sousChoixId: "sur-fin",
    aide: "m² SHON",
    pour: ["surelevation"],
    qteDefaut: (s) => s,
  },
  {
    code: "OCREN-15",
    label: "Rénovation patrimoniale / haussmannienne complète",
    groupe: "Global",
    aide: "m² SHAB concernés",
    pour: ["renovation_haussmannien"],
    qteDefaut: (s) => s,
    coche: true,
  },
  {
    code: "OCERP-01",
    label: "Aménagement boutique / retail clé en main",
    groupe: "Commerce / ERP",
    aide: "m² de surface",
    pour: ["amenagement_commercial"],
    qteDefaut: (s) => s,
    coche: true,
  },
  {
    code: "OCERP-02",
    label: "Local commercial coque nue → prêt à exploiter",
    groupe: "Commerce / ERP",
    aide: "m² de surface",
    pour: ["amenagement_commercial"],
    qteDefaut: () => 0,
  },
  {
    code: "OCERP-03",
    label: "Mise en accessibilité PMR (ERP existant)",
    groupe: "Accessibilité ERP",
    aide: "forfait",
    pour: ["amenagement_commercial", "chr_restaurant", "erp_sante"],
    qteDefaut: () => 0,
  },
  {
    code: "OCERP-10",
    label: "Cuisine professionnelle CHR clé en main",
    groupe: "CHR / Restaurant",
    aide: "m² de cuisine (~30 % de la surface par défaut)",
    pour: ["chr_restaurant"],
    qteDefaut: (s) => Math.round(s * 0.3),
    coche: true,
  },
  {
    code: "OCERP-11",
    label: "Sanitaires publics ERP H/F + PMR",
    groupe: "CHR / Restaurant",
    aide: "nombre de blocs",
    pour: ["chr_restaurant", "amenagement_commercial", "erp_sante"],
    qteDefaut: () => 1,
  },
  {
    code: "OCERP-20",
    label: "Salle(s) de soin seule(s)",
    groupe: "ERP santé",
    aide: "m² des salles uniquement",
    pour: ["erp_sante"],
    qteDefaut: (s) => Math.round(s * 0.5),
  },
  {
    code: "OCMAC-01",
    label: "Maison maçonnée — hors d'eau / hors d'air",
    groupe: "Maison maçonnée",
    aide: "m² SHAB",
    pour: ["neuf_maconne"],
    qteDefaut: (s) => s,
    coche: true,
  },
  {
    code: "OCMAC-02",
    label: "Maison maçonnée — clé en main TCE",
    groupe: "Maison maçonnée",
    aide: "m² SHAB",
    pour: ["neuf_maconne"],
    qteDefaut: (s) => s,
  },
  {
    code: "OCTER-01",
    label: "Aménagement plateau de bureaux clé en main",
    groupe: "Tertiaire / bureaux",
    aide: "m² de plateau",
    pour: ["amenagement_tertiaire"],
    qteDefaut: (s) => s,
    coche: true,
  },
  {
    code: "OCTER-10",
    label: "Kitchenette / tisanerie tertiaire",
    groupe: "Tertiaire / bureaux",
    aide: "nombre",
    pour: ["amenagement_tertiaire"],
    qteDefaut: () => 0,
  },
  {
    code: "ISO-08",
    label: "Combles perdus — soufflage R≥7",
    groupe: "Enveloppe",
    sousGroupe: "Isolation toiture",
    sousChoixId: "iso-combles",
    aide: "m² de plancher de combles",
    pour: ["renovation_maison", "renovation_energetique"],
    qteDefaut: () => 0,
    eligible55: true,
  },
  {
    code: "ISO-09",
    label: "Rampants — entre/sous chevrons R≥6",
    groupe: "Enveloppe",
    sousGroupe: "Isolation toiture",
    sousChoixId: "iso-combles",
    aide: "m² de rampants",
    pour: ["renovation_maison", "renovation_energetique"],
    qteDefaut: () => 0,
    eligible55: true,
  },
  {
    code: "PLO-42",
    label: "VMC simple flux hygro B",
    groupe: "Lots techniques",
    sousGroupe: "Ventilation (VMC)",
    sousChoixId: "vmc",
    aide: "nombre de logements",
    pour: ["renovation_appartement", "renovation_maison", "renovation_energetique"],
    qteDefaut: () => 1,
  },
  {
    code: "PLO-98",
    label: "VMC double flux haut rendement",
    groupe: "Lots techniques",
    sousGroupe: "Ventilation (VMC)",
    sousChoixId: "vmc",
    aide: "nombre de logements",
    pour: ["renovation_appartement", "renovation_maison", "renovation_energetique"],
    qteDefaut: () => 1,
    eligible55: true,
  },
  {
    code: "RS-16",
    label: "Parquet point de Hongrie (chêne massif)",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "m² de parquet",
    pour: ["renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "RS-17",
    label: "Parquet bâtons rompus / chevrons",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "m² de parquet",
    pour: ["renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "RS-19",
    label: "Rénovation parquet existant (ponçage + vitrification)",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "m² de parquet",
    pour: ["renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "CLO-40",
    label: "Cloisons amovibles mélaminé/métal",
    groupe: "Tertiaire / bureaux",
    sousGroupe: "Cloisonnement",
    sousChoixId: "cloison-ter",
    aide: "m² de cloison",
    pour: ["amenagement_tertiaire"],
    qteDefaut: () => 0,
  },
  {
    code: "CLO-41",
    label: "Cloisons vitrées toute hauteur",
    groupe: "Tertiaire / bureaux",
    sousGroupe: "Cloisonnement",
    sousChoixId: "cloison-ter",
    aide: "m² de cloison",
    pour: ["amenagement_tertiaire"],
    qteDefaut: () => 0,
  },
  {
    code: "CVC-90",
    label: "Climatisation VRF / détente directe",
    groupe: "Tertiaire / bureaux",
    sousGroupe: "Climatisation",
    sousChoixId: "clim-ter",
    aide: "m² traité",
    pour: ["amenagement_tertiaire"],
    qteDefaut: (s) => s,
  },
  {
    code: "CVC-91",
    label: "Centrale double flux (CTA)",
    groupe: "Tertiaire / bureaux",
    sousGroupe: "Climatisation",
    sousChoixId: "clim-ter",
    aide: "m² traité",
    pour: ["amenagement_tertiaire"],
    qteDefaut: (s) => s,
  },
  {
    code: "ENS-01",
    label: "Caisson lumineux LED",
    groupe: "Commerce / ERP",
    sousGroupe: "Enseigne",
    aide: "ml d'enseigne",
    pour: ["amenagement_commercial"],
    qteDefaut: () => 0,
  },
  {
    code: "ENS-02",
    label: "Lettres boîtier / relief",
    groupe: "Commerce / ERP",
    sousGroupe: "Enseigne",
    aide: "nombre de lettres",
    pour: ["amenagement_commercial"],
    qteDefaut: () => 0,
  },
  {
    code: "ENS-03",
    label: "Vitrophanie / covering",
    groupe: "Commerce / ERP",
    sousGroupe: "Enseigne",
    aide: "m² de vitrine",
    pour: ["amenagement_commercial"],
    qteDefaut: () => 0,
  },
  {
    code: "VRD-03",
    label: "Raccordement assainissement collectif",
    groupe: "Maison maçonnée",
    sousGroupe: "Assainissement",
    sousChoixId: "assainissement",
    aide: "raccordement",
    pour: ["neuf_maconne"],
    qteDefaut: () => 1,
  },
  {
    code: "VRD-04",
    label: "Filière ANC (fosse + épandage)",
    groupe: "Maison maçonnée",
    sousGroupe: "Assainissement",
    sousChoixId: "assainissement",
    aide: "installation",
    pour: ["neuf_maconne"],
    qteDefaut: () => 1,
  },
  {
    code: "OCREN-16",
    label: "ITE bardage ventilé (ossature rapportée)",
    groupe: "Enveloppe",
    sousGroupe: "Isolation des murs",
    sousChoixId: "iso-murs",
    aide: "m² de façade",
    pour: ["renovation_maison", "renovation_energetique"],
    qteDefaut: () => 0,
    eligible55: true,
  },
  {
    code: "OCREN-20",
    label: "Studio / locatif — rafraîchissement complet",
    groupe: "Global",
    aide: "m² SHAB",
    pour: ["renovation_studio"],
    qteDefaut: (s) => s,
  },
  {
    code: "RS-60",
    label: "Réfection sols complète (dépose + ragréage + revêtement + plinthes)",
    groupe: "Pièces",
    aide: "m² de sol",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio", "renovation_haussmannien", "adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "OCREN-21",
    label: "Buanderie / cellier clé en main",
    groupe: "Pièces",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio", "renovation_haussmannien", "adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "OCERP-21",
    label: "Cabinet médical complet clé en main",
    groupe: "ERP santé",
    aide: "m² de cabinet",
    pour: ["erp_sante"],
    qteDefaut: (s) => s,
    coche: true,
  },
  {
    code: "OCERP-22",
    label: "Bloc accessibilité ERP à la carte",
    groupe: "Accessibilité ERP",
    aide: "forfait",
    pour: ["amenagement_commercial", "chr_restaurant", "erp_sante"],
    qteDefaut: () => 0,
  },
  {
    code: "OCERP-23",
    label: "Mise en sécurité incendie ERP (BAES + alarme + extincteurs)",
    groupe: "Accessibilité ERP",
    aide: "forfait",
    pour: ["amenagement_commercial", "chr_restaurant", "erp_sante"],
    qteDefaut: () => 0,
  },
  {
    code: "OCERP-30",
    label: "Comptoir caisse / banque d'accueil",
    groupe: "Commerce / ERP",
    aide: "ml",
    pour: ["amenagement_commercial"],
    qteDefaut: () => 0,
  },
  {
    code: "OCERP-31",
    label: "Cabine d'essayage clé en main",
    groupe: "Commerce / ERP",
    aide: "nombre de cabines",
    pour: ["amenagement_commercial"],
    qteDefaut: () => 0,
  },
  {
    code: "OCERP-32",
    label: "Linéaire de présentation (gondoles / étagères)",
    groupe: "Commerce / ERP",
    aide: "ml",
    pour: ["amenagement_commercial"],
    qteDefaut: () => 0,
  },
  {
    code: "OCERP-40",
    label: "Climatisation boutique (PAC réversible)",
    groupe: "Commerce / ERP",
    aide: "m² traité",
    pour: ["amenagement_commercial"],
    qteDefaut: (s) => s,
  },
  {
    code: "OCTER-20",
    label: "Baie de brassage VDI + cœur de réseau",
    groupe: "Tertiaire / bureaux",
    aide: "forfait",
    pour: ["amenagement_tertiaire"],
    qteDefaut: () => 0,
  },
  {
    code: "OCTER-21",
    label: "Salle de réunion équipée clé en main",
    groupe: "Tertiaire / bureaux",
    aide: "nombre de salles",
    pour: ["amenagement_tertiaire"],
    qteDefaut: () => 0,
  },
  {
    code: "OCCHR-30",
    label: "Comptoir / bar de service CHR",
    groupe: "CHR / Restaurant",
    aide: "ml de bar",
    pour: ["chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "OCCHR-40",
    label: "Extraction + compensation cuisine ERP",
    groupe: "CHR / Restaurant",
    aide: "nombre d'installations",
    pour: ["chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "OCCHR-50",
    label: "Sécurité gaz + extinction de hotte",
    groupe: "CHR / Restaurant",
    aide: "forfait",
    pour: ["chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "OCCHR-60",
    label: "Chambres froides + production frigorifique",
    groupe: "CHR / Restaurant",
    aide: "nombre d'enceintes",
    pour: ["chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "OCNEUF-20",
    label: "Garage / annexe maçonné(e) clé en main",
    groupe: "Annexes & extérieurs",
    aide: "m²",
    pour: ["neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "OCNEUF-21",
    label: "Carport / abri ossature bois",
    groupe: "Annexes & extérieurs",
    aide: "m²",
    pour: ["neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "OCNEUF-22",
    label: "Terrasse extérieure dallée",
    groupe: "Annexes & extérieurs",
    aide: "m²",
    pour: ["neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "OCNEUF-23",
    label: "Aménagement extérieur / VRD de finition",
    groupe: "Annexes & extérieurs",
    aide: "m²",
    pour: ["neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "OCPMR-18",
    label: "Pack adaptation logement PMR / senior",
    groupe: "Pièces",
    aide: "forfait",
    pour: ["adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "OCPMR-16",
    label: "Baignoire → douche italienne PMR",
    groupe: "Pièces",
    aide: "nombre",
    pour: ["adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "OCPMR-17",
    label: "WC adapté PMR / senior",
    groupe: "Pièces",
    aide: "nombre",
    pour: ["adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "OCPMR-19",
    label: "Monte-escalier siège PMR",
    groupe: "Accessibilité ERP",
    aide: "nombre",
    pour: ["adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "OCPMR-20",
    label: "Plateforme élévatrice PMR",
    groupe: "Accessibilité ERP",
    aide: "nombre",
    pour: ["adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "PREP-30",
    label: "Audit énergétique réglementaire (DPE + MaPrimeRénov')",
    groupe: "Global",
    sousGroupe: "Préparation & études",
    aide: "nombre",
    pour: ["renovation_maison", "renovation_energetique", "renovation_appartement"],
    qteDefaut: () => 1,
  },
  {
    code: "PREP-31",
    label: "Test d'infiltrométrie (blower door)",
    groupe: "Global",
    sousGroupe: "Préparation & études",
    aide: "nombre",
    pour: ["renovation_energetique", "renovation_maison", "neuf_maconne"],
    qteDefaut: () => 1,
  },
  {
    code: "PREP-07",
    label: "Constat d'huissier avant travaux (copro / mitoyens)",
    groupe: "Global",
    sousGroupe: "Préparation & études",
    aide: "nombre",
    pour: ["renovation_haussmannien"],
    qteDefaut: () => 1,
  },
  {
    code: "PREP-06",
    label: "Plans architecturaux + dépôt PC / déclaration préalable",
    groupe: "Global",
    sousGroupe: "Préparation & études",
    aide: "nombre",
    pour: ["adaptation_pmr", "extension", "surelevation", "neuf_maconne", "erp_sante"],
    qteDefaut: () => 1,
  },
  {
    code: "PREP-05",
    label: "Étude géotechnique de sol (mission G2 AVP/PRO)",
    groupe: "Global",
    sousGroupe: "Préparation & études",
    aide: "nombre",
    pour: ["extension", "surelevation", "neuf_maconne"],
    qteDefaut: () => 1,
  },
  {
    code: "PREP-24",
    label: "Mission BET structure complète (note de calcul + plans + suivi)",
    groupe: "Global",
    sousGroupe: "Préparation & études",
    aide: "nombre",
    pour: ["extension", "surelevation", "neuf_maconne"],
    qteDefaut: () => 1,
  },
  {
    code: "MEN-02",
    label: "Pose cuisine équipée en kit (raccordements TCE)",
    groupe: "Pièces",
    sousGroupe: "Agencement & optimisation",
    aide: "nombre",
    pour: ["renovation_studio", "renovation_appartement", "renovation_maison"],
    qteDefaut: () => 1,
  },
  {
    code: "PIE-04",
    label: "Tablette marbre cheminée sur mesure (remplacement)",
    groupe: "Pièces",
    sousGroupe: "Cheminée marbre",
    aide: "nombre",
    pour: ["renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "PIE-03",
    label: "Cheminée marbre — dépose soigneuse + repose",
    groupe: "Pièces",
    sousGroupe: "Cheminée marbre (1 au choix)",
    sousChoixId: "cheminee-marbre",
    aide: "nombre",
    pour: ["renovation_haussmannien"],
    qteDefaut: () => 1,
  },
  {
    code: "PIE-02",
    label: "Cheminée marbre — nettoyage + lustrage en place",
    groupe: "Pièces",
    sousGroupe: "Cheminée marbre (1 au choix)",
    sousChoixId: "cheminee-marbre",
    aide: "nombre",
    pour: ["renovation_haussmannien"],
    qteDefaut: () => 1,
  },
  {
    code: "RS-15",
    label: "Tomettes / terre cuite ancienne (dito existant)",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "nombre",
    pour: ["renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "PEINT-03",
    label: "Peinture complète maison",
    groupe: "Pièces",
    sousGroupe: "Peinture (forfait global)",
    aide: "nombre",
    pour: ["renovation_maison", "neuf_maconne"],
    qteDefaut: () => 1,
  },
  {
    code: "RS-09",
    label: "Parquet toutes essences (fourniture + pose)",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio", "neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "RS-10",
    label: "Carrelage grès cérame rectifié grand format",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "neuf_maconne", "renovation_studio"],
    qteDefaut: () => 0,
  },
  {
    code: "RS-13",
    label: "Sol PVC clipsable LVT",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio", "adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "RS-18",
    label: "Sol béton ciré / microciment",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "renovation_maison", "neuf_maconne", "amenagement_commercial", "amenagement_tertiaire"],
    qteDefaut: () => 0,
  },
  {
    code: "RS-03",
    label: "Parquet contrecollé chêne huilé",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "nombre",
    pour: ["renovation_maison", "renovation_appartement", "renovation_studio"],
    qteDefaut: () => 0,
  },
  {
    code: "RS-20",
    label: "Sol stratifié clipsable AC4/AC5",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "nombre",
    pour: ["renovation_maison", "renovation_appartement", "renovation_studio"],
    qteDefaut: () => 0,
  },
  {
    code: "RS-12",
    label: "Carrelage grès 75×75 rectifié",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "PLO-92",
    label: "Douche italienne plain-pied (forme de pente + étanchéité SEL)",
    groupe: "Pièces",
    sousGroupe: "Salle de bains à la carte (PMR)",
    aide: "nombre",
    pour: ["adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "PLO-94",
    label: "Mitigeur thermostatique de douche anti-brûlure",
    groupe: "Pièces",
    sousGroupe: "Salle de bains à la carte (PMR)",
    aide: "nombre",
    pour: ["adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "PLO-90",
    label: "Barre d'appui PMR inox/époxy (droite/coudée) sur renfort",
    groupe: "Pièces",
    sousGroupe: "Salle de bains à la carte (PMR)",
    aide: "nombre",
    pour: ["adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "PLO-91",
    label: "Siège de douche rabattable mural PMR sur renfort",
    groupe: "Pièces",
    sousGroupe: "Salle de bains à la carte (PMR)",
    aide: "nombre",
    pour: ["adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "CLO-10",
    label: "Création de cloison BA13 phonique",
    groupe: "Murs & plafonds",
    sousGroupe: "Cloisonnement",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien", "renovation_studio"],
    qteDefaut: () => 1,
  },
  {
    code: "CLO-32",
    label: "Cloisons de distribution BA13 (Rw≥46 dB)",
    groupe: "Murs & plafonds",
    sousGroupe: "Cloisonnement",
    aide: "nombre",
    pour: ["renovation_maison", "renovation_appartement"],
    qteDefaut: () => 0,
  },
  {
    code: "CLO-08",
    label: "Faux-plafond BA13 plan (prêt à peindre)",
    groupe: "Murs & plafonds",
    sousGroupe: "Faux-plafond (1 au choix)",
    sousChoixId: "faux-plafond",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "renovation_maison", "renovation_studio", "amenagement_commercial", "amenagement_tertiaire", "erp_sante"],
    qteDefaut: () => 0,
  },
  {
    code: "CLO-06",
    label: "Faux-plafond acoustique BA13 + TECSOUND (spots intégrés)",
    groupe: "Murs & plafonds",
    sousGroupe: "Faux-plafond (1 au choix)",
    sousChoixId: "faux-plafond",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "chr_restaurant", "amenagement_tertiaire", "erp_sante"],
    qteDefaut: () => 0,
  },
  {
    code: "RM-15",
    label: "Peinture murs (au m²)",
    groupe: "Murs & plafonds",
    sousGroupe: "Peinture (au m²)",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien", "renovation_studio", "surelevation", "extension", "amenagement_commercial", "chr_restaurant", "amenagement_tertiaire", "adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "RM-16",
    label: "Peinture plafonds (au m²)",
    groupe: "Murs & plafonds",
    sousGroupe: "Peinture (au m²)",
    aide: "m² concernés",
    pour: ["renovation_studio", "renovation_appartement", "renovation_haussmannien", "amenagement_tertiaire", "renovation_maison", "adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "RM-14",
    label: "Pose papier peint (fourni client)",
    groupe: "Murs & plafonds",
    sousGroupe: "Peinture (au m²)",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "PEINT-01",
    label: "Peinture complète appartement",
    groupe: "Murs & plafonds",
    sousGroupe: "Peinture (forfait global)",
    aide: "nombre",
    pour: ["renovation_appartement"],
    qteDefaut: () => 1,
  },
  {
    code: "RM-20",
    label: "Faïence murale pleine hauteur (cuisine / SDB / soins)",
    groupe: "Murs & plafonds",
    sousGroupe: "Revêtement mural",
    aide: "nombre",
    pour: ["neuf_maconne", "amenagement_commercial", "chr_restaurant", "erp_sante", "renovation_appartement", "renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "STAFF-01",
    label: "Restauration corniches / moulures existantes",
    groupe: "Murs & plafonds",
    sousGroupe: "Staff & modénatures",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "STAFF-02",
    label: "Corniches staff neuves sur tracé",
    groupe: "Murs & plafonds",
    sousGroupe: "Staff & modénatures",
    aide: "nombre",
    pour: ["renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "STAFF-03",
    label: "Rosaces de plafond staff",
    groupe: "Murs & plafonds",
    sousGroupe: "Staff & modénatures",
    aide: "nombre",
    pour: ["renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "STAFF-04",
    label: "Moulures murales / cimaises / soubassements staff",
    groupe: "Murs & plafonds",
    sousGroupe: "Staff & modénatures",
    aide: "nombre",
    pour: ["renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "MEX-20",
    label: "Baie coulissante alu RPT 2 vantaux (L≤2,4 m)",
    groupe: "Enveloppe",
    sousGroupe: "Baie de liaison / grande ouverture (1 au choix)",
    sousChoixId: "baie-ext",
    aide: "nombre",
    pour: ["extension", "neuf_maconne", "renovation_maison", "renovation_appartement", "surelevation"],
    qteDefaut: () => 0,
  },
  {
    code: "MEX-21",
    label: "Baie coulissante alu 3 vantaux / 2 rails (L≤3,6 m)",
    groupe: "Enveloppe",
    sousGroupe: "Baie de liaison / grande ouverture (1 au choix)",
    sousChoixId: "baie-ext",
    aide: "nombre",
    pour: ["extension", "renovation_maison", "surelevation", "neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "MEX-22",
    label: "Baie alu à galandage (vantail escamotable)",
    groupe: "Enveloppe",
    sousGroupe: "Baie de liaison / grande ouverture (1 au choix)",
    sousChoixId: "baie-ext",
    aide: "nombre",
    pour: ["extension", "renovation_maison", "renovation_haussmannien", "neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "RAV-05",
    label: "Toiture-terrasse — étanchéité EPDM + isolant",
    groupe: "Enveloppe",
    sousGroupe: "Isolation toiture",
    aide: "nombre",
    pour: ["renovation_energetique", "renovation_maison"],
    qteDefaut: () => 0,
    eligible55: true,
  },
  {
    code: "MEX-23",
    label: "Fenêtres triple vitrage Uw≤0,9 (haute performance)",
    groupe: "Menuiseries extérieures",
    sousGroupe: "Fenêtres (1 au choix)",
    sousChoixId: "fenetre-ext",
    aide: "nombre",
    pour: ["renovation_energetique", "renovation_maison", "neuf_maconne", "renovation_appartement"],
    qteDefaut: () => 0,
    eligible55: true,
  },
  {
    code: "MEX-10",
    label: "Fenêtres bois 2 vantaux petits bois (dito existant)",
    groupe: "Enveloppe",
    sousGroupe: "Menuiseries patrimoniales",
    aide: "nombre",
    pour: ["renovation_haussmannien"],
    qteDefaut: () => 0,
    eligible55: true,
  },
  {
    code: "MEX-01",
    label: "Porte-fenêtre / porte bois 1V à doucine (dito existant)",
    groupe: "Enveloppe",
    sousGroupe: "Menuiseries patrimoniales",
    aide: "nombre",
    pour: ["renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "MEN-05",
    label: "Pont de lit MDF sur-mesure (penderies + éclairage tête de lit)",
    groupe: "Menuiseries intérieures",
    sousGroupe: "Agencement chambre",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "MEN-03",
    label: "Bibliothèque sur-mesure MDF toute hauteur (à peindre, LED)",
    groupe: "Menuiseries intérieures",
    sousGroupe: "Bibliothèque / rangement toute hauteur (1 au choix)",
    sousChoixId: "men-biblio",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "MEN-07",
    label: "Bibliothèque sur-mesure placage chêne (LED)",
    groupe: "Menuiseries intérieures",
    sousGroupe: "Bibliothèque / rangement toute hauteur (1 au choix)",
    sousChoixId: "men-biblio",
    aide: "nombre",
    pour: ["renovation_haussmannien", "renovation_appartement", "renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "MEN-17",
    label: "Portes intérieures (fourniture + pose)",
    groupe: "Menuiseries intérieures",
    sousGroupe: "Portes intérieures (type — 1 au choix)",
    sousChoixId: "men-porte-int",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien", "renovation_studio", "adaptation_pmr", "extension", "surelevation", "neuf_maconne", "amenagement_tertiaire"],
    qteDefaut: () => 0,
  },
  {
    code: "MEN-11",
    label: "Portes à galandage à peindre (passage 73 cm)",
    groupe: "Menuiseries intérieures",
    sousGroupe: "Portes intérieures (type — 1 au choix)",
    sousChoixId: "men-porte-int",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien", "neuf_maconne", "extension"],
    qteDefaut: () => 0,
  },
  {
    code: "MEN-10",
    label: "Portes coulissantes en applique (rail apparent, à peindre)",
    groupe: "Menuiseries intérieures",
    sousGroupe: "Portes intérieures (type — 1 au choix)",
    sousChoixId: "men-porte-int",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_studio", "renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "MEN-18",
    label: "Portes coulissantes galandage bois design",
    groupe: "Menuiseries intérieures",
    sousGroupe: "Portes intérieures (type — 1 au choix)",
    sousChoixId: "men-porte-int",
    aide: "nombre",
    pour: ["renovation_haussmannien", "renovation_appartement", "renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "MEN-06",
    label: "Porte à galandage (passage élargi)",
    groupe: "Menuiseries intérieures",
    sousGroupe: "Portes spéciales",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "adaptation_pmr", "amenagement_tertiaire"],
    qteDefaut: () => 0,
  },
  {
    code: "MEN-16",
    label: "Fenêtres PVC double vitrage (4/16/4 argon)",
    groupe: "Menuiseries extérieures",
    sousGroupe: "Fenêtres (1 au choix)",
    sousChoixId: "fenetre-ext",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio", "renovation_haussmannien", "renovation_energetique", "extension", "surelevation", "neuf_maconne"],
    qteDefaut: () => 0,
    eligible55: true,
  },
  {
    code: "MEX-06",
    label: "Fenêtre de toit (Velux) + store",
    groupe: "Menuiseries extérieures",
    sousGroupe: "Fenêtres de toit",
    aide: "nombre",
    pour: ["surelevation", "renovation_maison", "renovation_haussmannien", "extension"],
    qteDefaut: () => 0,
  },
  {
    code: "MEN-14",
    label: "Fenêtre de toit / Velux + modif. charpente (118×114, stores)",
    groupe: "Menuiseries extérieures",
    sousGroupe: "Fenêtres de toit",
    aide: "nombre",
    pour: ["renovation_maison", "surelevation"],
    qteDefaut: () => 1,
  },
  {
    code: "MEX-11",
    label: "Volets roulants micro-perforés (occultation)",
    groupe: "Menuiseries extérieures",
    sousGroupe: "Occultation / volets",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio", "renovation_energetique", "neuf_maconne", "extension"],
    qteDefaut: () => 0,
  },
  {
    code: "MEX-24",
    label: "Porte d'entrée alu/acier isolante",
    groupe: "Menuiseries extérieures",
    sousGroupe: "Porte d'entrée (1 au choix)",
    sousChoixId: "mex-porte-entree",
    aide: "nombre",
    pour: ["renovation_maison", "renovation_energetique", "neuf_maconne", "extension"],
    qteDefaut: () => 1,
    eligible55: true,
  },
  {
    code: "MEX-02",
    label: "Porte d'entrée alu thermolaquée RAL (1 vantail)",
    groupe: "Menuiseries extérieures",
    sousGroupe: "Porte d'entrée (1 au choix)",
    sousChoixId: "mex-porte-entree",
    aide: "nombre",
    pour: ["renovation_maison", "extension", "neuf_maconne"],
    qteDefaut: () => 1,
  },
  {
    code: "AGEN-14",
    label: "Bibliothèque sur-mesure toute hauteur",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Bibliothèque & séjour",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "renovation_maison", "amenagement_tertiaire"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-15",
    label: "Meuble TV / banc média sur-mesure",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Bibliothèque & séjour",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "renovation_maison", "renovation_studio"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-16",
    label: "Bibliothèque + porte coulissante miroir sur-mesure (ébéniste)",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Bibliothèque & séjour",
    aide: "nombre",
    pour: ["renovation_haussmannien", "renovation_appartement", "renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-17",
    label: "Habillage de niche / renfoncement sur-mesure",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Bibliothèque & séjour",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-08",
    label: "Îlot central de cuisine sur-mesure",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Cuisine sur-mesure",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-09",
    label: "Colonne four/frigo encastrée sur-mesure",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Cuisine sur-mesure",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-10",
    label: "Meuble haut vitré / vitrine sur-mesure",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Cuisine sur-mesure",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-27",
    label: "Crédence assortie au plan (même matériau, H 60 cm)",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Cuisine sur-mesure",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-03",
    label: "Dressing ouvert sur-mesure",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Dressing / rangements (1 au choix)",
    sousChoixId: "agen-dressing",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "neuf_maconne", "renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-04",
    label: "Dressing fermé haut de gamme (chêne plaqué, LED)",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Dressing / rangements (1 au choix)",
    sousChoixId: "agen-dressing",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-02",
    label: "Placard portes coulissantes sur-mesure",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Dressing / rangements (1 au choix)",
    sousChoixId: "agen-dressing",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "renovation_studio", "renovation_maison", "adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-01",
    label: "Placard intégré sur-mesure (portes battantes)",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Dressing / rangements (1 au choix)",
    sousChoixId: "agen-dressing",
    aide: "nombre",
    pour: ["renovation_maison", "renovation_appartement", "renovation_haussmannien", "renovation_studio", "adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-18",
    label: "Vestiaire d'entrée sur-mesure (MDF laqué, LED, tiroirs push)",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Entrée, chambre & bureau",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-19",
    label: "Banc / banquette sur-mesure avec coffre de rangement",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Entrée, chambre & bureau",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-36",
    label: "Option — façade laquée haut de gamme (RAL spécial, soft-touch)",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Options & étude",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-38",
    label: "Option — étude + plans d'exécution agencement",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Options & étude",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien", "amenagement_tertiaire", "amenagement_commercial"],
    qteDefaut: () => 1,
  },
  {
    code: "AGEN-25",
    label: "Plan de travail Dekton / céramique",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Plan de travail & crédence (1 au choix)",
    sousChoixId: "agen-plan",
    aide: "nombre",
    pour: ["renovation_maison", "renovation_appartement", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-26",
    label: "Plan de travail pierre (quartz / granit)",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Plan de travail & crédence (1 au choix)",
    sousChoixId: "agen-plan",
    aide: "nombre",
    pour: ["renovation_maison", "renovation_appartement", "neuf_maconne", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-24",
    label: "Plan de travail compact massif (Trespa / Compact)",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Plan de travail & crédence (1 au choix)",
    sousChoixId: "agen-plan",
    aide: "nombre",
    pour: ["renovation_maison", "renovation_appartement", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-23",
    label: "Plan de travail stratifié compact (HPL/Fenix) ép.12 mm",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Plan de travail & crédence (1 au choix)",
    sousChoixId: "agen-plan",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien", "renovation_studio"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-11",
    label: "Meuble vasque suspendu sur-mesure (hydrofuge, tiroirs Blum)",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Salle de bains sur-mesure",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-12",
    label: "Colonne / rangement SDB sur-mesure laqué hydrofuge",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Salle de bains sur-mesure",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-13",
    label: "Miroir LED sur-mesure (cadre/habillage intégré)",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Salle de bains sur-mesure",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-20",
    label: "Tête de lit sur-mesure (MDF à peindre)",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Tête de lit / couchage (1 au choix)",
    sousChoixId: "agen-tete",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "renovation_maison", "renovation_studio"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-21",
    label: "Tête de lit capitonnée tissu",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Tête de lit / couchage (1 au choix)",
    sousChoixId: "agen-tete",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-22",
    label: "Lit-estrade / couchage sur-mesure avec rangements",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Tête de lit / couchage (1 au choix)",
    sousChoixId: "agen-tete",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien", "renovation_studio"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-28",
    label: "Verrière atelier sur-mesure",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Verrière, claustra & habillage",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "renovation_maison", "extension", "chr_restaurant", "amenagement_tertiaire", "renovation_studio"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-29",
    label: "Claustra / séparation tasseaux bois",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Verrière, claustra & habillage",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "chr_restaurant", "renovation_maison", "renovation_studio", "amenagement_tertiaire"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-31",
    label: "Porte à galandage habillée assortie agencement",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Verrière, claustra & habillage",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-32",
    label: "Habillage radiateur / cache-conduit sur-mesure ajouré",
    groupe: "Agencement sur-mesure",
    sousGroupe: "Verrière, claustra & habillage",
    aide: "nombre",
    pour: ["renovation_haussmannien", "renovation_appartement", "renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "CLO-33",
    label: "Faux-plafond rampant + laine de bois (combles aménagés)",
    groupe: "Aménagement intérieur",
    sousGroupe: "Combles & cloisonnement",
    aide: "nombre",
    pour: ["renovation_maison", "surelevation"],
    qteDefaut: () => 0,
  },
  {
    code: "MEN-30",
    label: "Escalier intérieur bois (création / remplacement)",
    groupe: "Aménagement intérieur",
    sousGroupe: "Escalier (1 au choix)",
    sousChoixId: "escalier-maison",
    aide: "nombre",
    pour: ["renovation_maison", "surelevation", "neuf_maconne", "renovation_haussmannien", "extension"],
    qteDefaut: () => 0,
  },
  {
    code: "MEN-20",
    label: "Remise en état escalier existant",
    groupe: "Aménagement intérieur",
    sousGroupe: "Escalier (1 au choix)",
    sousChoixId: "escalier-maison",
    aide: "nombre",
    pour: ["renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "SER-11",
    label: "Garde-corps trémie / escalier acier",
    groupe: "Aménagement intérieur",
    sousGroupe: "Garde-corps & sécurisation",
    aide: "nombre",
    pour: ["renovation_maison", "surelevation", "renovation_haussmannien", "extension", "neuf_maconne", "amenagement_tertiaire"],
    qteDefaut: () => 0,
  },
  {
    code: "SER-13",
    label: "Garde-corps verre + pinces inox (trémie / terrasse)",
    groupe: "Aménagement intérieur",
    sousGroupe: "Garde-corps & sécurisation",
    aide: "nombre",
    pour: ["neuf_maconne", "amenagement_tertiaire", "renovation_maison", "renovation_haussmannien", "renovation_appartement", "extension", "surelevation"],
    qteDefaut: () => 0,
  },
  {
    code: "CHAR-11",
    label: "Charpente traditionnelle bois (réfection)",
    groupe: "Couverture & charpente",
    sousGroupe: "Charpente & évacuations",
    aide: "nombre",
    pour: ["renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "CHAR-03",
    label: "Gouttières zinc demi-rondes",
    groupe: "Couverture & charpente",
    sousGroupe: "Charpente & évacuations",
    aide: "nombre",
    pour: ["renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "CHAR-12",
    label: "Réfection couverture tuiles (écran HPV + faîtage ventilé)",
    groupe: "Couverture & charpente",
    sousGroupe: "Toiture (1 au choix)",
    sousChoixId: "couverture-maison",
    aide: "nombre",
    pour: ["renovation_maison", "neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "CHAR-05",
    label: "Charpente + couverture zinc (extension / toiture)",
    groupe: "Couverture & charpente",
    sousGroupe: "Toiture (1 au choix)",
    sousChoixId: "couverture-maison",
    aide: "nombre",
    pour: ["renovation_maison", "neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "PLO-64",
    label: "Chaudière gaz à condensation murale",
    groupe: "Lots techniques",
    sousGroupe: "Chauffage",
    sousChoixId: "chauffage",
    aide: "nombre",
    pour: ["renovation_maison", "renovation_appartement", "renovation_energetique"],
    qteDefaut: () => 1,
  },
  {
    code: "PLO-65",
    label: "Chaudière gaz condensation sol + ECS",
    groupe: "Lots techniques",
    sousGroupe: "Chauffage",
    sousChoixId: "chauffage",
    aide: "nombre",
    pour: ["renovation_maison", "renovation_haussmannien"],
    qteDefaut: () => 1,
  },
  {
    code: "PLO-60",
    label: "PAC air-eau 6-8 kW (chauffage + ECS, dimensionnée)",
    groupe: "Lots techniques",
    sousGroupe: "Chauffage",
    sousChoixId: "chauffage",
    aide: "nombre",
    pour: ["renovation_energetique", "renovation_maison", "renovation_appartement"],
    qteDefaut: () => 1,
    eligible55: true,
  },
  {
    code: "PLO-61",
    label: "PAC air-eau 10-12 kW (chauffage + ECS, dimensionnée)",
    groupe: "Lots techniques",
    sousGroupe: "Chauffage",
    sousChoixId: "chauffage",
    aide: "nombre",
    pour: ["renovation_energetique", "renovation_maison"],
    qteDefaut: () => 1,
    eligible55: true,
  },
  {
    code: "CVC-10",
    label: "Climatisation réversible monosplit 2,5 kW (chaud + froid)",
    groupe: "Lots techniques",
    sousGroupe: "Chauffage",
    sousChoixId: "chauffage",
    aide: "nombre",
    pour: ["renovation_studio", "renovation_appartement"],
    qteDefaut: () => 0,
  },
  {
    code: "CVC-73",
    label: "Gainable réversible 14 kW triphasé (froid + chaud)",
    groupe: "Lots techniques",
    sousGroupe: "Chauffage",
    sousChoixId: "chauffage",
    aide: "nombre",
    pour: ["renovation_maison"],
    qteDefaut: () => 1,
  },
  {
    code: "CVC-11",
    label: "Climatisation réversible — 1 pièce (split mural)",
    groupe: "Lots techniques",
    sousGroupe: "Climatisation réversible (1 au choix)",
    sousChoixId: "clim-appart",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "renovation_energetique", "surelevation", "extension"],
    qteDefaut: () => 0,
  },
  {
    code: "CVC-20",
    label: "Climatisation réversible — multi-split 2 pièces",
    groupe: "Lots techniques",
    sousGroupe: "Climatisation réversible (1 au choix)",
    sousChoixId: "clim-appart",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "CVC-21",
    label: "Climatisation réversible — multi-split 3 pièces",
    groupe: "Lots techniques",
    sousGroupe: "Climatisation réversible (1 au choix)",
    sousChoixId: "clim-appart",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien", "renovation_maison", "renovation_energetique"],
    qteDefaut: () => 0,
  },
  {
    code: "CVC-70",
    label: "Climatisation invisible à condensation à eau (sans groupe ext.)",
    groupe: "Lots techniques",
    sousGroupe: "Climatisation réversible (1 au choix)",
    sousChoixId: "clim-appart",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_haussmannien"],
    qteDefaut: () => 0,
  },
  {
    code: "CVC-22",
    label: "Climatisation réversible multi-split 4 pièces",
    groupe: "Lots techniques",
    sousGroupe: "Climatisation réversible (1 au choix)",
    sousChoixId: "clim-appart",
    aide: "nombre",
    pour: ["renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "EL-31",
    label: "Coffret de communication / VDI multimédia (grade 2/3)",
    groupe: "Lots techniques",
    sousGroupe: "Courants faibles & confort",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_studio", "renovation_haussmannien"],
    qteDefaut: () => 1,
  },
  {
    code: "EL-51",
    label: "Liaison équipotentielle locaux de soins (groupe 1, NF C 15-211)",
    groupe: "Lots techniques",
    sousGroupe: "Courants forts / faibles ERP",
    aide: "nombre",
    pour: ["erp_sante"],
    qteDefaut: () => 0,
  },
  {
    code: "EL-53",
    label: "Baie de brassage VDI 19\\\" + cœur de réseau (cabinet)",
    groupe: "Lots techniques",
    sousGroupe: "Courants forts / faibles ERP",
    aide: "nombre",
    pour: ["erp_sante"],
    qteDefaut: () => 0,
  },
  {
    code: "PLO-68",
    label: "Ballon thermodynamique 200L (ECS) COP≥2,9",
    groupe: "Lots techniques",
    sousGroupe: "Eau chaude sanitaire (1 au choix)",
    sousChoixId: "ecs-appart",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_energetique", "renovation_maison", "renovation_studio", "neuf_maconne"],
    qteDefaut: () => 1,
    eligible55: true,
  },
  {
    code: "PLO-69",
    label: "Ballon thermodynamique 270L (ECS) COP≥3,0",
    groupe: "Lots techniques",
    sousGroupe: "Eau chaude sanitaire (1 au choix)",
    sousChoixId: "ecs-appart",
    aide: "nombre",
    pour: ["renovation_energetique", "renovation_maison"],
    qteDefaut: () => 1,
    eligible55: true,
  },
  {
    code: "PLO-02",
    label: "Chauffe-eau électrique (ECS)",
    groupe: "Lots techniques",
    sousGroupe: "Eau chaude sanitaire (1 au choix)",
    sousChoixId: "ecs-appart",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_studio", "renovation_maison"],
    qteDefaut: () => 1,
  },
  {
    code: "EL-05",
    label: "Tableau électrique neuf appartement (TGBT + CONSUEL)",
    groupe: "Lots techniques",
    sousGroupe: "Électricité — niveau d'intervention (1 au choix)",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_studio", "renovation_haussmannien"],
    qteDefaut: () => 1,
  },
  {
    code: "EL-08",
    label: "Électricité complète maison + GTL + CONSUEL",
    groupe: "Lots techniques",
    sousGroupe: "Électricité — niveau d'intervention (1 au choix)",
    aide: "nombre",
    pour: ["neuf_maconne", "renovation_maison"],
    qteDefaut: () => 1,
  },
  {
    code: "PLO-72",
    label: "Chape fluide anhydrite sur plancher chauffant",
    groupe: "Lots techniques",
    sousGroupe: "Émetteurs (1 au choix)",
    aide: "m² concernés",
    pour: ["neuf_maconne"],
    qteDefaut: (s) => s,
  },
  {
    code: "PLO-70",
    label: "Plancher chauffant hydraulique basse température",
    groupe: "Lots techniques",
    sousGroupe: "Émetteurs (1 au choix)",
    sousChoixId: "emetteurs-maison",
    aide: "m² concernés",
    pour: ["renovation_maison", "extension", "neuf_maconne", "renovation_haussmannien", "renovation_energetique"],
    qteDefaut: (s) => s,
  },
  {
    code: "PLO-74",
    label: "Radiateurs eau chaude (jeu complet)",
    groupe: "Lots techniques",
    sousGroupe: "Émetteurs (1 au choix)",
    sousChoixId: "emetteurs-maison",
    aide: "nombre",
    pour: ["renovation_maison", "surelevation", "extension", "neuf_maconne", "renovation_appartement", "renovation_haussmannien", "renovation_energetique"],
    qteDefaut: () => 0,
  },
  {
    code: "EL-55",
    label: "Tableau divisionnaire extension + raccordement au TGBT existant",
    groupe: "Lots techniques",
    sousGroupe: "Lots techniques de l'extension",
    aide: "nombre",
    pour: ["extension", "surelevation"],
    qteDefaut: () => 1,
  },
  {
    code: "PLO-44",
    label: "Réseaux EF/ECS complets (extension)",
    groupe: "Lots techniques",
    sousGroupe: "Lots techniques de l'extension",
    aide: "nombre",
    pour: ["extension", "surelevation", "neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "CVC-12",
    label: "Climatisation réversible — split mural 5 kW A+++ (extension)",
    groupe: "Lots techniques",
    sousGroupe: "Lots techniques de l'extension",
    aide: "nombre",
    pour: ["extension"],
    qteDefaut: () => 0,
  },
  {
    code: "PLO-82",
    label: "Régulation multizone chauffage connectée (3 zones)",
    groupe: "Lots techniques",
    sousGroupe: "Pilotage & régulation",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien", "renovation_energetique"],
    qteDefaut: () => 1,
  },
  {
    code: "EL-01",
    label: "Électricité — distribution générale aux normes NF C 15-100",
    groupe: "Lots techniques",
    sousGroupe: "Sécurité technique",
    aide: "nombre",
    pour: ["adaptation_pmr", "surelevation", "extension"],
    qteDefaut: () => 0,
  },
  {
    code: "PLO-78",
    label: "Adoucisseur d'eau",
    groupe: "Lots techniques",
    sousGroupe: "Traitement & réseau d'eau",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien", "neuf_maconne"],
    qteDefaut: () => 1,
  },
  {
    code: "CVC-95",
    label: "VMC simple flux hygro B (logement)",
    groupe: "Lots techniques",
    sousGroupe: "Ventilation (VMC)",
    sousChoixId: "vmc",
    aide: "nombre",
    pour: ["renovation_studio", "renovation_haussmannien", "adaptation_pmr"],
    qteDefaut: () => 1,
  },
  {
    code: "PREP-01",
    label: "Installation & repli de chantier",
    groupe: "Préparation & dépose",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien", "adaptation_pmr", "renovation_studio", "renovation_energetique", "surelevation", "extension", "neuf_maconne", "amenagement_commercial", "chr_restaurant", "amenagement_tertiaire", "erp_sante"],
    qteDefaut: () => 1,
    coche: true,
  },
  {
    code: "PREP-12",
    label: "Protection ouvrages + ménage de fin de chantier",
    groupe: "Préparation & dépose",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien", "renovation_studio", "adaptation_pmr", "amenagement_commercial", "amenagement_tertiaire", "chr_restaurant"],
    qteDefaut: () => 1,
  },
  {
    code: "DEMO-08",
    label: "Dépose des cloisons non conservées",
    groupe: "Préparation & dépose",
    aide: "nombre",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien", "renovation_studio", "surelevation", "amenagement_commercial", "chr_restaurant", "amenagement_tertiaire", "erp_sante"],
    qteDefaut: () => 1,
  },
  {
    code: "DEMO-28",
    label: "Dépose globale revêtement de sol (carrelage / parquet)",
    groupe: "Préparation & dépose",
    aide: "m² concernés",
    pour: ["renovation_appartement", "renovation_maison", "renovation_haussmannien", "renovation_studio", "amenagement_commercial"],
    qteDefaut: (s) => s,
  },
  {
    code: "DEMO-05",
    label: "Dépose cuisine existante (consignation réseaux)",
    groupe: "Préparation & dépose",
    sousGroupe: "Dépose & curage",
    aide: "nombre",
    pour: ["renovation_studio", "renovation_appartement", "renovation_haussmannien", "chr_restaurant", "renovation_maison"],
    qteDefaut: () => 1,
  },
  {
    code: "DEMO-10",
    label: "Dépose salle de bains existante",
    groupe: "Préparation & dépose",
    sousGroupe: "Dépose & curage",
    aide: "nombre",
    pour: ["renovation_studio", "renovation_appartement", "renovation_haussmannien", "adaptation_pmr", "renovation_maison"],
    qteDefaut: () => 1,
  },
  {
    code: "DEMO-19",
    label: "Dépose plafond suspendu lames PVC existant",
    groupe: "Préparation & dépose",
    sousGroupe: "Dépose & curage",
    aide: "m² concernés",
    pour: ["amenagement_tertiaire"],
    qteDefaut: (s) => s,
  },
  {
    code: "MAC-17",
    label: "Ouverture de liaison en façade existante + poutre métal (selon BET)",
    groupe: "Structure",
    sousGroupe: "Liaison au bâtiment existant",
    aide: "nombre",
    pour: ["extension"],
    qteDefaut: () => 0,
  },
  {
    code: "MP-07",
    label: "Création de trémie d'escalier (découpe plancher + chevêtre + étaiement)",
    groupe: "Structure",
    sousGroupe: "Liaison au bâtiment existant",
    aide: "nombre",
    pour: ["extension", "surelevation"],
    qteDefaut: () => 0,
  },
  {
    code: "CHAR-01",
    label: "Dépose partielle charpente/couverture (jonction extension)",
    groupe: "Structure",
    sousGroupe: "Raccord toiture à la jonction (1 au choix)",
    sousChoixId: "liaison-toit",
    aide: "nombre",
    pour: ["extension"],
    qteDefaut: () => 0,
  },
  {
    code: "CHAR-02",
    label: "Reprise charpente-couverture à la jonction (EP + gouttière)",
    groupe: "Structure",
    sousGroupe: "Raccord toiture à la jonction (1 au choix)",
    sousChoixId: "liaison-toit",
    aide: "nombre",
    pour: ["extension"],
    qteDefaut: () => 0,
  },
  {
    code: "DEMO-01",
    label: "Décaissement / terrassement terre végétale + évacuation",
    groupe: "Structure",
    sousGroupe: "Terrassement & fondations",
    aide: "nombre",
    pour: ["extension", "neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "DEMO-04",
    label: "Terrassement + préparation de plateforme (concassé + grave + géotextile)",
    groupe: "Structure",
    sousGroupe: "Terrassement & fondations",
    aide: "m² concernés",
    pour: ["extension", "neuf_maconne"],
    qteDefaut: (s) => s,
  },
  {
    code: "OCMOB-14",
    label: "Fondations + dalle d'extension (à décocher du forfait HE-HA)",
    groupe: "Structure",
    sousGroupe: "Terrassement & fondations",
    aide: "m² concernés",
    pour: ["extension"],
    qteDefaut: (s) => s,
  },
  {
    code: "VRD-02",
    label: "Branchement / raccordement eau potable",
    groupe: "VRD & raccordements",
    aide: "nombre",
    pour: ["extension", "neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "VRD-01",
    label: "Tranchée + fourreaux réseaux secs (EDF / télécom)",
    groupe: "VRD & raccordements",
    aide: "nombre",
    pour: ["extension", "neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "CVC-72",
    label: "Chauffage / clim gainable du nouveau niveau (7 kW)",
    groupe: "Surélévation ossature bois",
    sousGroupe: "Chauffage du niveau",
    aide: "nombre",
    pour: ["surelevation", "neuf_maconne", "renovation_maison"],
    qteDefaut: () => 1,
  },
  {
    code: "SER-10",
    label: "Escalier métal limon central + marches bois",
    groupe: "Surélévation ossature bois",
    sousGroupe: "Escalier d'accès",
    aide: "nombre",
    pour: ["surelevation", "neuf_maconne", "renovation_maison", "renovation_haussmannien", "extension"],
    qteDefaut: () => 1,
  },
  {
    code: "OCMOB-13",
    label: "Ossature bois — hors d'air + isolation + plâtrerie (prêt pour lots techniques)",
    groupe: "Surélévation ossature bois",
    sousGroupe: "Structure & finition (1 au choix)",
    sousChoixId: "sur-fin",
    aide: "m² concernés",
    pour: ["surelevation"],
    qteDefaut: (s) => s,
  },
  {
    code: "CHAR-07",
    label: "Reprise d'interface toiture en surélévation (dépose couverture + arase + raccord étanchéité)",
    groupe: "Surélévation ossature bois",
    sousGroupe: "Travaux préparatoires niveau existant",
    aide: "nombre",
    pour: ["surelevation"],
    qteDefaut: () => 0,
  },
  {
    code: "MP-06",
    label: "Renforcement de mur porteur (étaiement + HEA + matage)",
    groupe: "Surélévation ossature bois",
    sousGroupe: "Travaux préparatoires niveau existant",
    aide: "nombre",
    pour: ["surelevation"],
    qteDefaut: () => 0,
  },
  {
    code: "MAC-32",
    label: "Hérisson + dallage BA isolé sur terre-plein",
    groupe: "Maison maçonnée",
    sousGroupe: "Soubassement / plancher bas",
    aide: "nombre",
    pour: ["neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "MEX-25",
    label: "Porte de garage sectionnelle motorisée",
    groupe: "Extérieurs maison",
    aide: "nombre",
    pour: ["renovation_maison", "neuf_maconne", "extension"],
    qteDefaut: () => 1,
  },
  {
    code: "MAC-21",
    label: "Terrasse extérieure dallée / carrelée",
    groupe: "Extérieurs maison",
    aide: "nombre",
    pour: ["renovation_maison"],
    qteDefaut: () => 0,
  },
  {
    code: "VRD-05",
    label: "Drainage périphérique + regard",
    groupe: "Extérieurs maison",
    aide: "nombre",
    pour: ["renovation_maison", "extension", "neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "SER-02",
    label: "Portail fer forgé (fourniture + pose)",
    groupe: "Extérieurs maison",
    sousGroupe: "Clôture & portail",
    aide: "nombre",
    pour: ["renovation_maison", "neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "SER-01",
    label: "Clôture fer forgé barreaudage",
    groupe: "Extérieurs maison",
    sousGroupe: "Clôture & portail",
    aide: "nombre",
    pour: ["renovation_maison", "neuf_maconne"],
    qteDefaut: () => 0,
  },
  {
    code: "CVC-33",
    label: "Cassette plafond 4 directions 3,5 kW (par unité)",
    groupe: "Commerce / ERP",
    sousGroupe: "Climatisation",
    aide: "nombre",
    pour: ["amenagement_commercial", "chr_restaurant", "erp_sante"],
    qteDefaut: () => 0,
  },
  {
    code: "DEVA-01",
    label: "Châssis vitrine alu/acier + vitrage de sécurité",
    groupe: "Commerce / ERP",
    sousGroupe: "Devanture / vitrine",
    aide: "nombre",
    pour: ["amenagement_commercial", "chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "DEVA-02",
    label: "Porte d'entrée commerciale vitrée 1V/2V",
    groupe: "Commerce / ERP",
    sousGroupe: "Devanture / vitrine",
    aide: "nombre",
    pour: ["amenagement_commercial", "chr_restaurant"],
    qteDefaut: () => 1,
  },
  {
    code: "DEVA-03",
    label: "Rideau métallique motorisé / grille extensible",
    groupe: "Commerce / ERP",
    sousGroupe: "Devanture / vitrine",
    aide: "nombre",
    pour: ["amenagement_commercial", "chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "DEVA-04",
    label: "Store-banne coffre motorisé",
    groupe: "Commerce / ERP",
    sousGroupe: "Devanture / vitrine",
    aide: "nombre",
    pour: ["amenagement_commercial", "chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "EL-50",
    label: "Tableau électrique ERP (TGBT + différentiels 30 mA + CONSUEL)",
    groupe: "Commerce / ERP",
    sousGroupe: "Électricité & éclairage",
    aide: "nombre",
    pour: ["amenagement_commercial", "chr_restaurant", "amenagement_tertiaire", "erp_sante"],
    qteDefaut: () => 1,
  },
  {
    code: "EL-56",
    label: "Éclairage scénographique sur rail LED orientable",
    groupe: "Commerce / ERP",
    sousGroupe: "Électricité & éclairage",
    aide: "nombre",
    pour: ["amenagement_commercial", "chr_restaurant", "amenagement_tertiaire"],
    qteDefaut: () => 0,
  },
  {
    code: "PLO-33",
    label: "Attente plomberie (point d'eau / lave-mains)",
    groupe: "Commerce / ERP",
    sousGroupe: "Plomberie & point d'eau",
    aide: "nombre",
    pour: ["amenagement_commercial", "amenagement_tertiaire"],
    qteDefaut: () => 0,
  },
  {
    code: "RS-23",
    label: "Sol PVC/lino commercial soudé U4 (en lés)",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "m² concernés",
    pour: ["amenagement_commercial", "erp_sante", "chr_restaurant", "amenagement_tertiaire"],
    qteDefaut: (s) => s,
  },
  {
    code: "RS-21",
    label: "Sol résine époxy/PU coulé",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "m² concernés",
    pour: ["amenagement_commercial", "chr_restaurant", "erp_sante", "amenagement_tertiaire"],
    qteDefaut: (s) => s,
  },
  {
    code: "RS-22",
    label: "Carrelage sol antidérapant R10/R11 (zone humide / PMR)",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "m² concernés",
    pour: ["amenagement_commercial", "chr_restaurant", "erp_sante"],
    qteDefaut: (s) => s,
  },
  {
    code: "CVC-92",
    label: "Ventilation mécanique ERP (extraction selon effectif)",
    groupe: "Commerce / ERP",
    sousGroupe: "Ventilation ERP",
    aide: "m² concernés",
    pour: ["amenagement_commercial", "chr_restaurant", "amenagement_tertiaire", "erp_sante"],
    qteDefaut: (s) => s,
  },
  {
    code: "PLO-95",
    label: "Bac à graisses / séparateur NF EN 1825",
    groupe: "CHR / Restaurant",
    sousGroupe: "Cuisine à la carte (hors clé en main)",
    aide: "nombre",
    pour: ["chr_restaurant"],
    qteDefaut: () => 1,
  },
  {
    code: "CHR-01",
    label: "Hotte professionnelle inox + bac à graisses (au ml)",
    groupe: "CHR / Restaurant",
    sousGroupe: "Cuisine à la carte (hors clé en main)",
    aide: "nombre",
    pour: ["chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "CHR-08",
    label: "Chambre froide positive (par enceinte)",
    groupe: "CHR / Restaurant",
    sousGroupe: "Cuisine à la carte (hors clé en main)",
    aide: "nombre",
    pour: ["chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "CHR-09",
    label: "Chambre froide négative (par enceinte)",
    groupe: "CHR / Restaurant",
    sousGroupe: "Cuisine à la carte (hors clé en main)",
    aide: "nombre",
    pour: ["chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "CHR-04",
    label: "Plonge professionnelle inox 2 bacs",
    groupe: "CHR / Restaurant",
    sousGroupe: "Cuisine à la carte (hors clé en main)",
    aide: "nombre",
    pour: ["chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "EL-45",
    label: "Tableau divisionnaire cuisine pro étanche IP55",
    groupe: "CHR / Restaurant",
    sousGroupe: "Électricité cuisine pro",
    aide: "nombre",
    pour: ["chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "EL-44",
    label: "Arrêt d'urgence cuisine ERP (coupure énergies)",
    groupe: "CHR / Restaurant",
    sousGroupe: "Électricité cuisine pro",
    aide: "nombre",
    pour: ["chr_restaurant"],
    qteDefaut: () => 1,
  },
  {
    code: "EL-43",
    label: "Départ force motrice cuisine pro (par équipement)",
    groupe: "CHR / Restaurant",
    sousGroupe: "Électricité cuisine pro",
    aide: "nombre",
    pour: ["chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "CVC-79",
    label: "Caisson d'extraction de buées cuisine en toiture",
    groupe: "CHR / Restaurant",
    sousGroupe: "Extraction cuisine (à la carte)",
    aide: "nombre",
    pour: ["chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "CVC-80",
    label: "Conduit d'extraction cuisine inox + gaine coupe-feu (au ml)",
    groupe: "CHR / Restaurant",
    sousGroupe: "Extraction cuisine (à la carte)",
    aide: "nombre",
    pour: ["chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "CHR-12",
    label: "Banquettes de salle sur-mesure (au ml)",
    groupe: "CHR / Restaurant",
    sousGroupe: "Mobilier & agencement salle",
    aide: "nombre",
    pour: ["chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "AGEN-33",
    label: "Banc de bureaux / bench intégré sur-mesure",
    groupe: "Tertiaire / bureaux",
    sousGroupe: "Agencement & accueil",
    aide: "nombre",
    pour: ["amenagement_tertiaire"],
    qteDefaut: () => 0,
  },
  {
    code: "CLO-42",
    label: "Bloc-porte vitré sur cloison amovible",
    groupe: "Tertiaire / bureaux",
    sousGroupe: "Cloisonnement",
    aide: "nombre",
    pour: ["amenagement_tertiaire"],
    qteDefaut: () => 0,
  },
  {
    code: "RS-26",
    label: "Sol tertiaire — dalles moquette plombantes / PVC en lés",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "m² concernés",
    pour: ["amenagement_tertiaire", "amenagement_commercial"],
    qteDefaut: (s) => s,
  },
  {
    code: "RS-24",
    label: "Faux-plancher technique sur vérins (dalles 600×600)",
    groupe: "Sols",
    sousGroupe: "Revêtement de sol (1 au choix)",
    sousChoixId: "sol",
    aide: "m² concernés",
    pour: ["amenagement_tertiaire"],
    qteDefaut: (s) => s,
  },
  {
    code: "ACC-01",
    label: "Bloc sanitaire PMR ERP complet",
    groupe: "Accessibilité ERP",
    sousGroupe: "Accès & sanitaires",
    aide: "nombre",
    pour: ["chr_restaurant", "amenagement_commercial"],
    qteDefaut: () => 0,
  },
  {
    code: "ACC-02",
    label: "Rampe d'accès extérieure PMR (pente ≤5 %) + main courante",
    groupe: "Accessibilité ERP",
    sousGroupe: "Accès & sanitaires",
    aide: "nombre",
    pour: ["adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "ACC-03",
    label: "Élargissement de passage de porte ≥0,90 m",
    groupe: "Accessibilité ERP",
    sousGroupe: "Circulation intérieure",
    aide: "nombre",
    pour: ["adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "SER-12",
    label: "Rampe d'escalier bois/métal (sur volée)",
    groupe: "Accessibilité ERP",
    sousGroupe: "Circulation intérieure",
    aide: "nombre",
    pour: ["adaptation_pmr"],
    qteDefaut: () => 0,
  },
  {
    code: "ACC-05",
    label: "Signalétique réglementaire ERP (braille/relief, pictos PMR, fléchage)",
    groupe: "Accessibilité ERP",
    sousGroupe: "Repérage & signalétique",
    aide: "nombre",
    pour: ["erp_sante", "amenagement_commercial", "chr_restaurant"],
    qteDefaut: () => 0,
  },
  {
    code: "SEC-06",
    label: "Mission coordination SSI / passage commission de sécurité",
    groupe: "Accessibilité ERP",
    sousGroupe: "Sécurité incendie ERP",
    aide: "nombre",
    pour: ["amenagement_commercial", "chr_restaurant", "erp_sante", "amenagement_tertiaire"],
    qteDefaut: () => 1,
  },
  {
    code: "SEC-05",
    label: "Bloc-porte coupe-feu EI30/EI60 + ferme-porte",
    groupe: "Accessibilité ERP",
    sousGroupe: "Sécurité incendie ERP",
    aide: "nombre",
    pour: ["erp_sante", "amenagement_commercial", "chr_restaurant"],
    qteDefaut: () => 0,
  },
];

/** Ordre canonique d'affichage des blocs (groupe) dans le wizard rapide. */
export const GROUPES_ORDRE: string[] = [
  "Global",
  "Pièces",
  "Murs & plafonds",
  "Sols",
  "Enveloppe",
  "Menuiseries intérieures",
  "Menuiseries extérieures",
  "Agencement sur-mesure",
  "Aménagement intérieur",
  "Couverture & charpente",
  "Lots techniques",
  "Préparation & dépose",
  "Structure",
  "VRD & raccordements",
  "Extension ossature bois",
  "Surélévation ossature bois",
  "Maison maçonnée",
  "Extérieurs maison",
  "Annexes & extérieurs",
  "Commerce / ERP",
  "CHR / Restaurant",
  "Tertiaire / bureaux",
  "ERP santé",
  "Accessibilité ERP",
];

/** Rang d'un bloc dans l'ordre canonique (999 si inconnu → en fin). */
export function ordreDuGroupe(groupe: string): number {
  const i = GROUPES_ORDRE.indexOf(groupe);
  return i === -1 ? 999 : i;
}

/**
 * Ouvrages proposés pour un type de projet donné.
 * Repli sur tout le catalogue si aucun ouvrage spécifique (robustesse).
 */
export function ouvragesPourType(type: TypeProjetRapide): OuvrageRapide[] {
  const filtres = OUVRAGES_RAPIDE.filter((o) => o.pour.includes(type));
  return filtres.length > 0 ? filtres : OUVRAGES_RAPIDE;
}

/** Types de rénovation de logement existant (TVA réduite éligible). */
const TYPES_RENO_LOGEMENT: TypeProjetRapide[] = [
  "renovation_appartement",
  "renovation_maison",
  "renovation_studio",
  "renovation_haussmannien",
  "renovation_energetique",
  "adaptation_pmr",
];

/** TVA par défaut suggérée selon le type de projet (Guide §2.1). */
export function tvaSuggeree(type: TypeProjetRapide): TauxTVA {
  // Énergétique + adaptation PMR = 5,5 % ; rénovation logement = 10 % ; neuf/extension/pro = 20 %.
  // (NB : la sélection réelle est arbitrée par tvaSuggereeSelection — bascule à 10 %
  //  dès qu'un poste non éligible est coché. Ici = suggestion de TYPE, étape 1.)
  if (type === "renovation_energetique" || type === "adaptation_pmr") return 5.5;
  if (TYPES_RENO_LOGEMENT.includes(type)) return 10;
  return 20;
}

/** Ouvrages d'amélioration énergétique (TVA 5,5 % si seuls, Guide §2.1 / CGI 278-0 bis A). */
export const CODES_ENERGETIQUES = new Set([
  "OCREN-04", // ITI
  "OCREN-05", // ITE
  "OCREN-10", // menuiseries isolantes
  "OCREN-14", // PAC air-eau
  "ISO-08", // combles soufflés
  "ISO-09", // rampants
  "PLO-98", // VMC double flux
  // OCREN-09 (ravalement non isolant) EXCLU : relève du 10 %, pas du 5,5 %.
]);

/** Ouvrages d'adaptation à la perte d'autonomie (TVA 5,5 % si seuls, CGI 278-0 bis A). */
export const CODES_ADAPTATION_PMR = new Set([
  "OCREN-13", // SDB PMR sécurisée
  "OCERP-03", // mise en accessibilité
  "OCPMR-16", // baignoire -> douche italienne
  "OCPMR-17", // WC adapté
  "OCPMR-18", // pack adaptation logement
  "OCPMR-19", // monte-escalier siège
  "OCPMR-20", // plateforme élévatrice PMR
]);

/**
 * TVA suggérée en tenant compte de la sélection :
 * - 5,5 % si rénovation logement et sélection 100 % énergétique ;
 * - 5,5 % si adaptation PMR et sélection 100 % postes d'adaptation ;
 * sinon règle par type.
 */
/** Ouvrage du catalogue rapide par code. */
export function ouvrageParCode(code: string): OuvrageRapide | undefined {
  return OUVRAGES_RAPIDE.find((o) => o.code === code);
}

/** Éligibilité TVA 5,5 % : attribut de l'ouvrage prioritaire, sinon set legacy. */
export function estEligible55(code: string): boolean {
  return ouvrageParCode(code)?.eligible55 ?? CODES_ENERGETIQUES.has(code);
}

export function tvaSuggereeSelection(
  type: TypeProjetRapide,
  codesActifs: string[],
): TauxTVA {
  if (codesActifs.length === 0) return tvaSuggeree(type);
  // 5,5 % UNIQUEMENT si la sélection est 100 % éligible (énergétique ou adaptation PMR).
  const tousEnergetiques =
    TYPES_RENO_LOGEMENT.includes(type) && codesActifs.every((c) => estEligible55(c));
  const tousPmr =
    type === "adaptation_pmr" && codesActifs.every((c) => CODES_ADAPTATION_PMR.has(c));
  if (tousEnergetiques || tousPmr) return 5.5;
  // Sinon : 10 % réno logement (y compris énergétique avec un poste non éligible), 20 % neuf/pro.
  return TYPES_RENO_LOGEMENT.includes(type) ? 10 : 20;
}

/** Ouvrages dont le périmètre recouvre celui d'un autre (risque double-comptage). */
const RECOUVREMENTS: Record<string, string[]> = {
  "OCREN-07": ["OCREN-06", "OCREN-11", "OCREN-12", "RS-09", "RS-10", "RS-13", "RS-18", "RS-03", "RS-20", "RS-12", "RM-15", "RM-16", "RM-14", "PEINT-01", "PEINT-03", "CLO-10", "CLO-32", "CLO-08", "CLO-06", "STAFF-01", "PLO-42", "PLO-98"],
  "OCMOB-10": ["OCMOB-09", "OCMOB-19", "RM-15", "MEN-17", "MEN-11", "PLO-44", "EL-55", "EL-01", "PLO-70", "PLO-74"],
  "OCMOB-16": ["OCMOB-19", "RM-15", "MEN-17", "MEN-11", "PLO-44", "EL-55", "EL-01", "PLO-70", "PLO-74"],
  "OCMOB-15": ["OCMOB-19", "RM-15", "MEN-17", "MEN-11", "PLO-44", "EL-55", "EL-01", "PLO-70", "PLO-74"],
  "OCMAC-03": ["OCMOB-19", "RM-15", "MEN-17", "MEN-11", "PLO-44", "EL-55", "EL-01", "PLO-70", "PLO-74"],
  "OCMOB-12": ["OCMOB-11", "OCMOB-19", "RM-15", "MEN-17", "CLO-33", "MEN-30", "SER-10", "SER-11", "SER-13", "MEN-14", "CVC-11", "CVC-72", "PLO-74", "PLO-44", "EL-01", "EL-55", "MEX-20", "MEX-21", "MEX-06"],
  "OCMOB-18": ["OCMOB-19", "RM-15", "MEN-17", "CLO-33", "MEN-30", "SER-10", "SER-11", "SER-13", "MEN-14", "CVC-11", "CVC-72", "PLO-74", "PLO-44", "EL-01", "EL-55", "MEX-20", "MEX-21", "MEX-06"],
  "OCMOB-17": ["OCMOB-19", "RM-15", "MEN-17", "CLO-33", "MEN-30", "SER-10", "SER-11", "SER-13", "MEN-14", "CVC-11", "CVC-72", "PLO-74", "PLO-44", "EL-01", "EL-55", "MEX-20", "MEX-21", "MEX-06"],
  "OCMAC-05": ["OCMOB-19", "RM-15", "MEN-17", "CLO-33", "MEN-30", "SER-10", "SER-11", "SER-13", "MEN-14", "CVC-11", "CVC-72", "PLO-74", "PLO-44", "EL-01", "EL-55", "MEX-20", "MEX-21", "MEX-06"],
  "OCMAC-02": ["OCMAC-01", "OCNEUF-20", "MAC-32", "DEMO-01", "DEMO-04", "CHAR-12", "CHAR-05", "EL-08", "PLO-44", "PLO-68", "PLO-70", "PLO-72", "PLO-74", "PLO-78", "CVC-72", "RS-09", "RS-10", "RS-18", "RM-20", "PEINT-03", "MEN-17", "MEN-11", "MEN-16", "MEN-30", "MEX-20", "MEX-21", "MEX-22", "MEX-02", "MEX-11", "MEX-24", "MEX-23", "SER-10", "SER-11", "SER-13", "AGEN-03", "AGEN-26", "VRD-01", "VRD-02", "VRD-03", "VRD-04", "VRD-05"],
  "OCREN-15": ["OCREN-07", "STAFF-01", "STAFF-02", "STAFF-03", "STAFF-04", "RS-16", "RS-17", "RS-15", "RS-19", "PIE-02", "PIE-03", "PIE-04", "RM-15", "RM-16", "CLO-08", "CLO-06", "DEMO-08", "DEMO-28", "EL-05"],
  "OCERP-10": ["OCCHR-40", "OCCHR-50", "PLO-95", "CHR-01", "CVC-79", "CVC-80", "EL-43", "EL-44", "EL-45"],
  "OCERP-21": ["OCERP-20", "RS-23", "RS-21", "RS-22", "RS-24", "RM-20", "CLO-06", "CLO-08", "EL-50", "EL-51", "CVC-33", "CVC-92"],
  "OCERP-03": ["OCERP-22", "ACC-01", "ACC-05"],
  "OCPMR-18": ["OCPMR-16", "OCPMR-17", "PLO-90", "PLO-91", "PLO-92", "PLO-94", "ACC-03", "DEMO-10"],
  "OCREN-05": ["OCREN-09"],
  "OCREN-16": ["OCREN-09"],
  "OCREN-20": ["RS-09", "RS-10", "RS-13", "RS-03", "RS-20", "RM-15", "RM-16", "CLO-08"],
  "OCERP-01": ["RS-23", "RS-50", "RS-21", "RS-22", "RS-18", "RS-26", "RM-15", "CLO-08", "EL-56", "DEMO-08", "PREP-12"],
  "OCERP-02": ["OCERP-01", "RS-23", "RS-50", "RS-21", "RS-22", "RS-18", "RS-26", "RM-15", "CLO-08", "EL-50", "EL-56", "PLO-33", "CVC-92", "DEMO-08"],
  "OCCHR-60": ["CHR-08", "CHR-09"],
  "OCERP-40": ["CVC-33"],
  "OCTER-01": ["CLO-40", "CLO-41", "CLO-42", "CLO-08", "CLO-06", "RS-24", "RS-26", "CVC-90", "CVC-91", "CVC-92", "OCTER-20", "EL-50", "EL-56"],
  "OCERP-20": ["RS-23", "RS-21", "RS-22", "EL-51"],
  "OCMOB-14": [],
  "OCMAC-01": ["MAC-32", "CHAR-12", "CHAR-05", "MEN-16", "MEX-23", "MEX-24", "MEX-02", "MEX-20", "MEX-21", "MEX-22", "MEX-11", "DEMO-01", "DEMO-04"],
  "OCPMR-16": ["PLO-90", "PLO-91", "PLO-92", "PLO-94", "DEMO-10"],
};

/**
 * Détecte les paires d'ouvrages cochés au périmètre recouvrant.
 * Retourne des messages d'alerte (non bloquants) pour l'UI.
 */
export function detecterRecouvrements(codesActifs: string[]): string[] {
  const set = new Set(codesActifs);
  const msgs: string[] = [];
  for (const [code, recouvre] of Object.entries(RECOUVREMENTS)) {
    if (!set.has(code)) continue;
    for (const r of recouvre) {
      if (set.has(r)) {
        const a = OUVRAGES_RAPIDE.find((o) => o.code === code)?.label ?? code;
        const b = OUVRAGES_RAPIDE.find((o) => o.code === r)?.label ?? r;
        msgs.push(`« ${a} » recouvre déjà « ${b} » — risque de double-comptage.`);
      }
    }
  }
  return msgs;
}

/** Sélection d'un ouvrage en mode rapide (code + quantité saisie). */
export interface SelectionRapide {
  code: string;
  qte: number;
}

/**
 * Génère les lignes de devis à partir des ouvrages sélectionnés.
 * `getPoste` résout un code BPU en poste (injecté pour rester pur/testable).
 * Les ouvrages à quantité nulle ou introuvables sont ignorés.
 */
export function genererLignesRapide(
  selections: SelectionRapide[],
  params: ParametresDevis,
  getPoste: (code: string) => PosteBPU | undefined,
): LigneDevis[] {
  const lignes: LigneDevis[] = [];
  for (const sel of selections) {
    if (!sel.qte || sel.qte <= 0) continue;
    const poste = getPoste(sel.code);
    if (!poste) continue;
    const ligne = ligneDepuisPoste(poste, params, sel.qte);
    // Ouvrage complet clé en main = quantité ferme : pas de coef conservateur.
    ligne.coefQte = 1;
    ligne.ferme = true;
    lignes.push(ligne);
  }
  return lignes;
}

/** Construit les sélections par défaut pour un type de projet + surface. */
export function selectionsDefaut(
  type: TypeProjetRapide,
  shab: number,
): Record<string, { actif: boolean; qte: number }> {
  const out: Record<string, { actif: boolean; qte: number }> = {};
  for (const o of ouvragesPourType(type)) {
    const qte = o.qteDefaut(shab);
    // Défaut coché : ouvrage marqué coche, ou poste « tête » du type spécialisé.
    const tete =
      (type === "renovation_energetique" && o.code === "OCREN-04") ||
      (type === "adaptation_pmr" && o.code === "OCREN-13");
    // Garde-fou : ne jamais ouvrir un ouvrage coché SANS quantité (état d'erreur).
    out[o.code] = { actif: (!!o.coche || tete) && qte > 0, qte };
  }
  return out;
}

// Réexport pour confort d'import côté UI.
export type { Gamme };
